modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License V3.0"
[[mods]] #mandatory
modId="hbm" #mandatory
version="${file.jarVersion}" #mandatory
displayName="HBM's Nuclear Tech - Rewrite Edition" #mandatory
authors="Mudz, TheRealM18, Alcater, Drillgon200, TheOriginalGolem, HBMMods/The Bobcat" #optional
description='''A mod all about nuclear physics and even nuclear-er explosions, now coming to you in 1.20.1!!
 Courtesy of the amazing Mudz, and everyone before him ;)
 (This is an early access mod. Alpha 1.8.21; There's lots of shit missing!!
  And probably a lot of bugs too!
  Report them in my discord: https://discord.gg/fkbaR7aefK (DO NOT BOTHER THE OTHER DEVELOPERS, THEY AREN'T WORKING ON THIS MOD))
  '''
[[dependencies.hbm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.4,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.hbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.hbm]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.7.2,)"
    ordering="AFTER"
    side="BOTH"
